### ISSUE TITLE
There was an error in evaluating the Pre-request Script:Error: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by karthikeyan-mac** [jamf/Classic-API-Postman-Collection#1]
I am using 10.35+ postman collection from here with Postman 9.25.0. I have updated the variables but I get the below error when trying to execute APIs

`There was an error in evaluating the Pre-request Script:Error: Unexpected token u in JSON at position 0`

**Comment by fortunst** [comment]
Are you defining variables at the collection level or as part of an environment? Try using an environment, if you're using the collection currently.

**Comment by karthikeyan-mac** [comment]
Thank you @fortunst. Adding the variable in environment level worked. I was defining at the collection level. Thanks
